apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: pe-owned-templates
  description: Templates and entities owned by the Platform Engineering team
spec:
  targets:
    - ./templates/deploy-application/template.yaml
    - ./templates/parasol-insurance-secured/template.yaml
    - ./templates/quarkus-rest-api/template.yaml
    - ./templates/request-kafka-topic/template.yaml
    - ./templates/request-kafka-user/template.yaml
    - ./templates/request-namespace/template.yaml
    - ./entities/system.yaml
    - ./entities/api.yaml
    - ./entities/components.yaml
    - ./entities/llm-inference-server/resource.yaml
