apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: parasol-insurance
  description: Parasol Insurance claims management application
  annotations:
    backstage.io/kubernetes-id: parasol-insurance
    janus-idp.io/tekton: parasol-insurance-build
    backstage.io/kubernetes-label-selector: app.kubernetes.io/name=parasol-insurance
    jira/project-key: PARASOL
    quay.io/repository-slug: parasol/parasol-insurance
spec:
  type: service
  lifecycle: production
  owner: devteam1
  system: parasol-insurance
  providesApis:
    - parasol-insurance-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: parasol-insurance-secured
  description: Parasol Insurance application with secured build pipeline
  annotations:
    backstage.io/kubernetes-id: parasol-insurance-secured
    backstage.io/kubernetes-label-selector: app.kubernetes.io/name=parasol-insurance-secured
    janus-idp.io/tekton: parasol-insurance-secured-build
    jira/project-key: PARASOL
    quay.io/repository-slug: parasol/parasol-insurance
spec:
  type: service
  lifecycle: production
  owner: devteam1
  system: parasol-insurance
  providesApis:
    - parasol-insurance-api
