apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: parasol-insurance-secured-listener
  namespace: ${{ values.namespace }}
spec:
  host: el-secured-${{ values.owner }}.${{ values.cluster_subdomain }}
  to:
    kind: Service
    name: el-parasol-insurance-secured-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
