apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: intake
  namespace: ${{ values.namespace }}
  labels:
    strimzi.io/cluster: parasol-kafka
spec:
  partitions: 1
  replicas: 1
