apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: parasol-insurance-secured-push
  namespace: ${{ values.namespace }}
spec:
  params:
    - name: git-revision
      type: string
  workspaces:
    - name: source
    - name: basic-auth
    - name: dockerconfig
    - name: sonar-credentials
  tasks:
    - name: clone-source
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      params:
        - name: URL
          value: "${{ values.source_repo }}"
        - name: REVISION
          value: $(params.git-revision)
        - name: SSL_VERIFY
          value: "false"
      workspaces:
        - name: output
          workspace: source
        - name: basic-auth
          workspace: basic-auth
    - name: build-and-push
      runAfter:
        - sonar-scan
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
      params:
        - name: IMAGE
          value: "${{ values.image_host }}/${{ values.image_organization }}/${{ values.image_name }}:${{ values.image_tag }}"
        - name: DOCKERFILE
          value: Containerfile
        - name: TLSVERIFY
          value: "false"
        - name: STORAGE_DRIVER
          value: vfs
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig
    - name: rollout-restart
      runAfter:
        - build-and-push
      taskRef:
        name: rollout-restart-secured
      params:
        - name: DEPLOYMENT
          value: parasol-insurance-secured
    - name: sonar-scan
      runAfter:
        - clone-source
      taskRef:
        name: sonar-scan-secured
      params:
        - name: SONAR_HOST_URL
          value: "http://sonarqube.sonarqube.svc:9000"
        - name: SONAR_PROJECT_KEY
          value: parasol-insurance
      workspaces:
        - name: source
          workspace: source
        - name: sonar-credentials
          workspace: sonar-credentials
