apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: parasol-insurance-secured-push
  namespace: ${{ values.namespace }}
spec:
  params:
    - name: git-revision
      type: string
  results:
    - name: ACS_IMAGE_SCAN_OUTPUT
      description: ACS vulnerability summary for Developer Hub
      value: $(tasks.acs-image-scan.results.SCAN_OUTPUT)
  workspaces:
    - name: source
    - name: basic-auth
    - name: dockerconfig
    - name: sonar-credentials
  tasks:
    - name: clone-source
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      params:
        - name: URL
          value: "${{ values.source_repo }}"
        - name: REVISION
          value: $(params.git-revision)
        - name: SSL_VERIFY
          value: "false"
      workspaces:
        - name: output
          workspace: source
        - name: basic-auth
          workspace: basic-auth
    # - name: sonar-scan
    #   runAfter:
    #     - clone-source
    #   taskRef:
    #     name: sonar-scan-secured
    #   params:
    #     - name: SONAR_HOST_URL
    #       value: "http://sonarqube.sonarqube.svc:9000"
    #     - name: SONAR_DASHBOARD_URL
    #       value: "https://sonarqube-sonarqube.${{ values.cluster_subdomain }}"
    #     - name: SONAR_PROJECT_KEY
    #       value: parasol-insurance
    #   workspaces:
    #     - name: source
    #       workspace: source
    #     - name: sonar-credentials
    #       workspace: sonar-credentials
    - name: build-and-push
      runAfter:
        - clone-source
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
      params:
        - name: IMAGE
          value: "${{ values.image_host }}/${{ values.image_organization }}/${{ values.image_name }}:${{ values.image_tag }}"
        - name: DOCKERFILE
          value: Containerfile
        - name: TLSVERIFY
          value: "false"
        - name: STORAGE_DRIVER
          value: vfs
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig
    - name: acs-image-scan
      runAfter:
        - build-and-push
      taskRef:
        name: acs-image-scan-secured
      params:
        - name: IMAGE
          value: "${{ values.image_host }}/${{ values.image_organization }}/${{ values.image_name }}:${{ values.image_tag }}"
    - name: acs-image-check
      runAfter:
        - build-and-push
      taskRef:
        name: acs-image-check-secured
      params:
        - name: IMAGE
          value: "${{ values.image_host }}/${{ values.image_organization }}/${{ values.image_name }}:${{ values.image_tag }}"
    - name: generate-sbom
      runAfter:
        - acs-image-scan
        - acs-image-check
      taskRef:
        name: generate-sbom-secured
      params:
        - name: IMAGE
          value: "${{ values.image_host }}/${{ values.image_organization }}/${{ values.image_name }}:${{ values.image_tag }}"
        - name: SOURCE_NAME
          value: "parasol-insurance-${{ values.branch }}"
        - name: SOURCE_VERSION
          value: $(params.git-revision)
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig
    - name: upload-sbom-to-tpa
      runAfter:
        - generate-sbom
      taskRef:
        name: upload-sbom-to-tpa-secured
      params:
        - name: LABEL_DEV
          value: "${{ values.dev_email }}"
        - name: LABEL_COMPONENT
          value: "parasol-insurance-secured-${{ values.owner }}"
      workspaces:
        - name: source
          workspace: source
    - name: rollout-restart
      runAfter:
        - upload-sbom-to-tpa
      taskRef:
        name: rollout-restart-secured
      params:
        - name: DEPLOYMENT
          value: parasol-insurance-secured
