apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka-user-${{ values.name }}
  description: ${{ values.description }}
  annotations:
    backstage.io/managed-by-location: url:https://${{ values.gitlab_host }}/rhdh/infra-app-of-apps/-/blob/main/kafka-users/${{ values.name }}.yaml
    kafka.io/user-name: ${{ values.name }}
  tags:
    - kafka
    - user
spec:
  type: kafka-user
  lifecycle: production
  owner: ${{ values.owner }}
