apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-deployer.name" . }}
  namespace: {{ include "app-deployer.namespace" . }}
  labels:
    {{- include "app-deployer.labels" . | nindent 4 }}
  annotations:
    app.openshift.io/vcs-uri: {{ .Values.app.vcsUri | quote }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "app-deployer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app-deployer.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "app-deployer.name" . }}
          image: {{ include "app-deployer.imageRef" . }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          {{- with .Values.app.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
