apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-deployer.name" . }}
  namespace: {{ include "app-deployer.namespace" . }}
  labels:
    {{- include "app-deployer.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "app-deployer.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
